-- CLINEVO SMART INBOX DATABASE
CREATE TABLE IF NOT EXISTS EMAIL_MESSAGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SENDER VARCHAR(500),
    SUBJECT VARCHAR(1000),
    BODY CLOB,
    RECEIVED_AT TIMESTAMP,
    STATUS VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DOCUMENT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL_ID BIGINT,
    FILE_NAME VARCHAR(500),
    DOCUMENT_TYPE VARCHAR(100),
    ORIGINAL_LINK VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (EMAIL_ID) REFERENCES EMAIL_MESSAGE(ID)
);

CREATE TABLE IF NOT EXISTS ANALYSIS_RESULT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_ID BIGINT,
    SUMMARY CLOB,
    HUMAN_REVIEW_REQUIRED BOOLEAN,
    PROCESSING_TIME_MS BIGINT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES DOCUMENT(ID)
);

CREATE TABLE IF NOT EXISTS CLASSIFICATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ANALYSIS_ID BIGINT,
    CATEGORY VARCHAR(100),
    CONFIDENCE DOUBLE,
    REASON VARCHAR(2000),
    FOREIGN KEY (ANALYSIS_ID) REFERENCES ANALYSIS_RESULT(ID)
);

CREATE TABLE IF NOT EXISTS EXTRACTED_FACT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ANALYSIS_ID BIGINT,
    FIELD_NAME VARCHAR(200),
    VALUE_TEXT VARCHAR(4000),
    CONFIDENCE DOUBLE,
    FOREIGN KEY (ANALYSIS_ID) REFERENCES ANALYSIS_RESULT(ID)
);

CREATE TABLE IF NOT EXISTS EVIDENCE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    FACT_ID BIGINT,
    SOURCE_TYPE VARCHAR(100),
    SOURCE_ID VARCHAR(500),
    PAGE_NUMBER INT,
    EVIDENCE_TEXT CLOB,
    CONFIDENCE DOUBLE,
    FOREIGN KEY (FACT_ID) REFERENCES EXTRACTED_FACT(ID)
);

CREATE TABLE IF NOT EXISTS REVIEW_ACTION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ANALYSIS_ID BIGINT,
    ACTION VARCHAR(100),
    ORIGINAL_CATEGORY VARCHAR(100),
    FINAL_CATEGORY VARCHAR(100),
    REVIEWER VARCHAR(200),
    NOTES VARCHAR(4000),
    ACTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ANALYSIS_ID) REFERENCES ANALYSIS_RESULT(ID)
);

CREATE TABLE IF NOT EXISTS PROCESSING_LOG (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    DOCUMENT_ID BIGINT,
    STAGE VARCHAR(200),
    PROCESSING_TIME_MS BIGINT,
    STATUS VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
