server.port=${PORT:8080}
spring.application.name=clinevo-smart-inbox-backend

spring.datasource.url=jdbc:h2:file:./data/clinevo
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

ai.service.url=${AI_SERVICE_URL:https://clinevo-smart-inbox-1.onrender.com}
